name: Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  buildandpush:
    uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@main
    with:
      imageName: apache-superset
      directory: products/sde-3rd-party/superset/docker-apache-superset
    secrets: inherit
